'use client';

import { useEffect, useRef } from 'react';

import { usePathname } from 'next/navigation';

import { projects } from '../data/projects';

/**
 * Monogram trail: dragging the cursor drops the six client marks in its wake, cycling in
 * order so a sweep across the page reveals all of them.
 *
 * The marks are IMPRINT's own six spec clients, generated by scripts/generate-monograms.mjs.
 * Real-world logos are deliberately not used — a studio site scattering trademarked marks
 * reads as a claim to have worked for those companies, and would undercut the six honest
 * case studies a scroll away.
 */
const SOURCES = projects.map((p) => `/monograms/${p.slug}.webp`);

/**
 * On a project route the trail is that ONE brand's mark. Cycling all six across a page
 * devoted to a single client reads as decoration; the brand's own mark reads as the page.
 * Home, 404 and the menu keep the six-brand cycle.
 */
function poolFor(pathname: string | null): string[] {
  const m = pathname?.match(/^\/work\/([^/]+)/);
  if (!m) return SOURCES;
  const one = projects.find((p) => p.slug === m[1]);
  return one ? [`/monograms/${one.slug}.webp`] : SOURCES;
}

/** Without a distance threshold the trail smears into mush on any slow pointer movement. */
const SPAWN_DISTANCE = 130;

/** Live pool cap. Transform and opacity only — no filters — so it stays on the compositor. */
const MAX_LIVE = 6;

const TILE = 90;
const IN_MS = 300;
const OUT_MS = 800;

export default function CursorTrail() {
  // The trail lives in the layout and never remounts, so the route has to be read reactively
  // — a pool captured at mount would keep showing the six-brand cycle after the first
  // client-side navigation into a project.
  const pathname = usePathname();
  const layerRef = useRef<HTMLDivElement>(null);

  // All of this lives in refs. setState on pointermove would re-render sixty times a second.
  const last = useRef({ x: 0, y: 0, set: false });
  const cursor = useRef(0);
  const live = useRef<HTMLImageElement[]>([]);

  useEffect(() => {
    const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
    const touch = window.matchMedia('(hover: none)').matches;
    if (reduced || touch) return;

    const layer = layerRef.current;
    if (!layer) return;

    const pool = poolFor(pathname);

    pool.forEach((src) => {
      const img = new Image();
      img.src = src;
    });

    /** Suppressed while a full-screen layer is up — the trail would be drawing behind it. */
    const suppressed = () => {
      const menu = document.querySelector('[data-menu-overlay]');
      if (menu?.getAttribute('data-open') === 'true') return true;
      const panel = document.querySelector('[data-transition-panel]');
      if (panel && panel.getAttribute('data-phase') !== 'idle') return true;
      return !!document.querySelector('[data-intro]');
    };

    const retire = (el: HTMLImageElement) => {
      const i = live.current.indexOf(el);
      if (i === -1) return;
      live.current.splice(i, 1);
      // Marked so the live pool can be told apart from tiles still playing their exit.
      el.dataset.exiting = '1';

      const base = el.dataset.base ?? '';
      const out = el.animate(
        [
          { opacity: 1, transform: `${base} translateY(0px) scale(1)` },
          { opacity: 0, transform: `${base} translateY(22px) scale(1.05)` },
        ],
        { duration: OUT_MS, easing: 'cubic-bezier(.16,1,.3,1)', fill: 'forwards' }
      );
      out.onfinish = () => el.remove();
      // If the animation never finishes — a backgrounded tab drops it — remove anyway, or
      // retired tiles accumulate in the DOM.
      window.setTimeout(() => el.remove(), OUT_MS + 400);
    };

    const spawn = (x: number, y: number) => {
      const el = document.createElement('img');
      const src = pool[cursor.current % pool.length];
      el.src = src;
      el.dataset.slug = src.replace(/^.*\/|\.webp$/g, '');
      cursor.current++;
      el.alt = '';
      el.setAttribute('aria-hidden', 'true');

      const rot = (Math.random() * 16 - 8).toFixed(2);
      const base = `translate(-50%, -50%) rotate(${rot}deg)`;
      el.dataset.base = base;

      Object.assign(el.style, {
        position: 'absolute',
        left: `${x}px`,
        top: `${y}px`,
        width: `${TILE}px`,
        height: `${TILE}px`,
        objectFit: 'cover',
        transform: base,
        opacity: '0',
        willChange: 'transform, opacity',
      } as Partial<CSSStyleDeclaration>);

      layer.appendChild(el);
      live.current.push(el);

      el.animate(
        [
          { opacity: 0, transform: `${base} scale(0.85)` },
          { opacity: 1, transform: `${base} scale(1)` },
        ],
        { duration: IN_MS, easing: 'cubic-bezier(.16,1,.3,1)', fill: 'forwards' }
      );

      window.setTimeout(() => retire(el), IN_MS + 140);
      while (live.current.length > MAX_LIVE) retire(live.current[0]);
    };

    const onMove = (e: PointerEvent) => {
      if (suppressed()) return;

      const { x, y, set } = last.current;
      if (!set) {
        last.current = { x: e.clientX, y: e.clientY, set: true };
        return;
      }
      const dx = e.clientX - x;
      const dy = e.clientY - y;
      if (dx * dx + dy * dy < SPAWN_DISTANCE * SPAWN_DISTANCE) return;

      last.current = { x: e.clientX, y: e.clientY, set: true };
      spawn(e.clientX, e.clientY);
    };

    window.addEventListener('pointermove', onMove, { passive: true });
    return () => {
      window.removeEventListener('pointermove', onMove);
      live.current.forEach((el) => el.remove());
      live.current = [];
    };
  }, [pathname]);

  return (
    <div
      ref={layerRef}
      aria-hidden="true"
      data-trail-layer=""
      style={{
        position: 'fixed',
        inset: 0,
        pointerEvents: 'none',
        overflow: 'hidden',
        // Above content and the veil, below the menu (9500) and the cursor disc (10001).
        zIndex: 9400,
      }}
    />
  );
}
