// Generated by scripts/ingest-brands.mjs — do not edit by hand.
// Brands absent from this map, or with null fields, fall back to generated artwork.
export type GalleryImage = { src: string; aspect: number };
export type BrandAssets = {
  logo: string | null;
  hero: string | null;
  gallery: GalleryImage[];
  keyedLogo: boolean;
  logoAspect?: number;
  logoInk?: string;
  logoMode?: string;
  logoClearPct?: number;
  logoRetention?: number;
  logoDebris?: number;
  heroW?: number;
  heroH?: number;
  accent: string | null;
  imageryLum: number | null;
  framing: 'dark' | 'light' | null;
  heroLowerLeftLum: number | null;
  heroTextShare: number | null;
};
export const brandAssets: Record<string, BrandAssets> = {
  "vyntrix": {
    "logo": "/brands/vyntrix/logo.webp",
    "hero": "/brands/vyntrix/hero.webp",
    "gallery": [
      {
        "src": "/brands/vyntrix/gallery-01.webp",
        "aspect": 0.819
      },
      {
        "src": "/brands/vyntrix/gallery-02.webp",
        "aspect": 1.333
      }
    ],
    "keyedLogo": true,
    "accent": null,
    "logoAspect": 2.136,
    "logoInk": "#edeae3",
    "logoMode": "dark-on-light",
    "logoClearPct": 88.3,
    "logoRetention": 0.994,
    "logoDebris": 0,
    "heroW": 1660,
    "heroH": 936,
    "imageryLum": 28.1,
    "framing": "dark",
    "heroLowerLeftLum": 13.2,
    "heroTextShare": 0
  },
  "vaelcron": {
    "logo": "/brands/vaelcron/logo.webp",
    "hero": "/brands/vaelcron/hero.webp",
    "gallery": [
      {
        "src": "/brands/vaelcron/gallery-01.webp",
        "aspect": 0.749
      },
      {
        "src": "/brands/vaelcron/gallery-02.webp",
        "aspect": 1.776
      }
    ],
    "keyedLogo": false,
    "accent": null,
    "logoAspect": 1.118,
    "logoInk": "#616162",
    "logoMode": "alpha",
    "logoClearPct": 28.1,
    "logoRetention": 0.999,
    "logoDebris": 44,
    "heroW": 804,
    "heroH": 450,
    "imageryLum": 111.1,
    "framing": "light",
    "heroLowerLeftLum": 141.5,
    "heroTextShare": 0
  },
  "rethread": {
    "logo": "/brands/rethread/logo.webp",
    "hero": "/brands/rethread/hero.webp",
    "gallery": [
      {
        "src": "/brands/rethread/gallery-01.webp",
        "aspect": 0.75
      },
      {
        "src": "/brands/rethread/gallery-02.webp",
        "aspect": 1.335
      },
      {
        "src": "/brands/rethread/gallery-03.webp",
        "aspect": 1.778
      }
    ],
    "keyedLogo": true,
    "accent": null,
    "logoAspect": 1.216,
    "logoInk": "#465640",
    "logoMode": "dark-on-light",
    "logoClearPct": 89.9,
    "logoRetention": 0.995,
    "logoDebris": 7,
    "heroW": 860,
    "heroH": 484,
    "imageryLum": 24.3,
    "framing": "dark",
    "heroLowerLeftLum": 21.7,
    "heroTextShare": 0
  },
  "voyaze": {
    "logo": "/brands/voyaze/logo.webp",
    "hero": "/brands/voyaze/hero.webp",
    "gallery": [
      {
        "src": "/brands/voyaze/gallery-01.webp",
        "aspect": 1
      },
      {
        "src": "/brands/voyaze/gallery-02.webp",
        "aspect": 1.333
      }
    ],
    "keyedLogo": true,
    "accent": null,
    "logoAspect": 1.133,
    "logoInk": "#837168",
    "logoMode": "dark-on-light",
    "logoClearPct": 83.2,
    "logoRetention": 0.991,
    "logoDebris": 37,
    "heroW": 912,
    "heroH": 512,
    "imageryLum": 169.5,
    "framing": "light",
    "heroLowerLeftLum": 191.1,
    "heroTextShare": 0
  },
  "voxaris": {
    "logo": "/brands/voxaris/logo.webp",
    "hero": "/brands/voxaris/hero.webp",
    "gallery": [
      {
        "src": "/brands/voxaris/gallery-01.webp",
        "aspect": 1
      },
      {
        "src": "/brands/voxaris/gallery-02.webp",
        "aspect": 1.327
      }
    ],
    "keyedLogo": true,
    "accent": null,
    "logoAspect": 1.135,
    "logoInk": "#6b5546",
    "logoMode": "bright-on-dark",
    "logoClearPct": 77,
    "logoRetention": 0.918,
    "logoDebris": 1052,
    "heroW": 736,
    "heroH": 412,
    "imageryLum": 23,
    "framing": "dark",
    "heroLowerLeftLum": 20.2,
    "heroTextShare": 0
  },
  "sentinel": {
    "logo": "/brands/sentinel/logo.webp",
    "hero": "/brands/sentinel/hero.webp",
    "gallery": [
      {
        "src": "/brands/sentinel/gallery-01.webp",
        "aspect": 0.751
      },
      {
        "src": "/brands/sentinel/gallery-02.webp",
        "aspect": 1.334
      }
    ],
    "keyedLogo": true,
    "accent": null,
    "logoAspect": 1.143,
    "logoInk": "#817c75",
    "logoMode": "bright-on-dark",
    "logoClearPct": 85.3,
    "logoRetention": 0.958,
    "logoDebris": 38,
    "heroW": 1122,
    "heroH": 632,
    "imageryLum": 119,
    "framing": "light",
    "heroLowerLeftLum": 180,
    "heroTextShare": 0
  }
};
