// Generated by scripts/fetch-context.mjs — do not edit by hand.
// Projects absent from this map simply render without a context photo.
//
// Empty: every brand now ships its own photography under public/brands, so the Wikimedia
// stand-ins and their attribution captions have been removed. Re-run the script for any
// brand that loses its real imagery.
export type ContextPhoto = { src: string; caption: string; source: string; query: string };
export const contextPhotos: Record<string, ContextPhoto> = {};
