// Generated by scripts/generate_frames.py — do not edit by hand.
// Counted from files on disk, so it can never drift from public/frames.
export const FRAME_COUNT = 180;
export const FRAME_DIR = '/frames';

export function framePath(index: number): string {
  return `${FRAME_DIR}/frame_${String(index + 1).padStart(4, '0')}.webp`;
}
