export type Project = {
  slug: string;
  name: string;
  sector: string;
  categories: string;
  year: number;
  role: string;
  summary: string;
  palette: [string, string, string, string];
  /** The one palette colour allowed to act as the brand's accent. */
  accent: string;
  typeface: string;
  monogram: string;
  problem: string;
  move: string;
  system: string;
  result: string;
  images: string[];
  /** 16:10 rendering of board 01, for the project-page hero. Cropping the 4:5 board to
   *  16:10 would undo the in-browser fit and slice the wordmark. */
  wordmarkWide: string;
  /**
   * Set where the wordmark is MEANT to run past the board edge, so the generator fits it to
   * more than the board width and the padding assertion exempts the axis it bleeds on. One
   * datum, two consumers — otherwise the generator and verify.mjs disagree about whether a
   * cropped glyph is the design or a defect.
   */
  wordmarkBleed?: 'horizontal';
};

/**
 * Board images are generated by scripts/generate-boards.mjs:
 *   -01 wordmark · -01w wordmark 16:10 · -02 colour · -03 application
 *   -04 type specimen · -05 construction · -06 lockups
 *
 * The type specimen is rendered at build time in each brand's real typeface, which is why
 * none of these six faces are loaded as web fonts. The site ships three faces, not nine.
 *
 * Monograms are two letters for every brand. Four of the six names begin with V, so a
 * single-letter mark would repeat four times across the cursor trail and the boards.
 *
 * Accents are deliberately spread around the wheel — volt 75°, gold 40°, forest 110°,
 * coral 12°, phosphor 160°, indigo 238° — so the work grid reads as six different clients
 * rather than six colourways of one.
 */
export const projects: Project[] = [
  {
    slug: 'vyntrix',
    name: 'VYNTRIX',
    sector: 'Performance Sneakers',
    categories: 'Identity / Packaging',
    year: 2025,
    role: 'Brand identity, art direction',
    summary: 'A stencil mark cut from the sole, and a volt line that means one thing.',
    palette: ['#1B1D1F', '#C6F24E', '#EDEAE3', '#7E8388'],
    accent: '#C6F24E',
    typeface: 'Archivo Black',
    monogram: 'VY',
    problem:
      'A sneaker label that made only sneakers, and was read as a label that only made one thing.',
    move:
      'Turn the constraint into the claim. If you make nothing else, the mark should look like it was cut from the sole.',
    system:
      'Stencil wordmark, a volt accent reserved for the outsole line and nothing else, a shoebox system that works flat-packed, and size typography legible at 20mm.',
    result:
      'The single-product story became the pitch rather than the gap. The stencil now appears on the shoe before it appears on the box.',
    images: [
      '/work/vyntrix-01.webp',
      '/work/vyntrix-02.webp',
      '/work/vyntrix-03.webp',
      '/work/vyntrix-04.webp',
      '/work/vyntrix-05.webp',
      '/work/vyntrix-06.webp',
    ],
    wordmarkWide: '/work/vyntrix-01w.webp',
    // Seven letters on one line, tracked tight, running off both edges with the V and the X
    // cropped. That IS the full-bleed system; a two-line break leaves a dead zone at the
    // right edge and reads as a fitting failure rather than a decision.
    wordmarkBleed: 'horizontal',
  },
  {
    slug: 'vaelcron',
    name: 'VAELCRON',
    sector: 'Haute Horology',
    categories: 'Identity / Art Direction',
    year: 2026,
    role: 'Brand identity, art direction',
    summary: 'An identity quieter than the watch, with margins wide enough to feel expensive.',
    palette: ['#0E0E10', '#9A7B3F', '#C9C6BF', '#F2EFE8'],
    accent: '#9A7B3F',
    typeface: 'Cormorant Garamond',
    monogram: 'VC',
    problem: 'A maison selling to two hundred people a year, marketing to two million.',
    move:
      'Stop shouting at the wrong room. Restraint is the product; the identity should be quieter than the watch.',
    system:
      'Wordmark set once and never repeated, a margin rule wide enough to feel expensive on any surface, gold used only on the dial index, and a photography direction of one object, one light.',
    result:
      'Every surface now assumes the reader already knows. The catalogue lost forty pages and gained a waiting list.',
    images: [
      '/work/vaelcron-01.webp',
      '/work/vaelcron-02.webp',
      '/work/vaelcron-03.webp',
      '/work/vaelcron-04.webp',
      '/work/vaelcron-05.webp',
      '/work/vaelcron-06.webp',
    ],
    wordmarkWide: '/work/vaelcron-01w.webp',
  },
  {
    slug: 'rethread',
    name: 'RETHREAD',
    sector: 'Circular Apparel',
    categories: 'Identity / Digital',
    year: 2026,
    role: 'Brand identity, art direction',
    summary: 'The buy-back moved out of the footer and onto the care label.',
    palette: ['#1E1F1B', '#2F3D30', '#D9D2C4', '#8A8474'],
    accent: '#2F3D30',
    typeface: 'Work Sans',
    monogram: 'RT',
    problem:
      'Buy-back was the whole business, and it was buried three clicks deep in the footer.',
    move:
      'Put the return on the label. If the garment can come back, the identity should say so while it is still on the rail.',
    system:
      'Wordmark, a care-label system carrying the buy-back terms in the garment itself, a stitched-in return code, and a resale surface that looks like the primary store rather than an outlet.',
    result:
      'The label became the marketing. Returns stopped being an afterthought and started being the reason people bought.',
    images: [
      '/work/rethread-01.webp',
      '/work/rethread-02.webp',
      '/work/rethread-03.webp',
      '/work/rethread-04.webp',
      '/work/rethread-05.webp',
      '/work/rethread-06.webp',
    ],
    wordmarkWide: '/work/rethread-01w.webp',
  },
  {
    slug: 'voyaze',
    name: 'VOYAZE',
    sector: 'Travel · The Ten Million',
    categories: 'Campaign / Digital',
    year: 2025,
    role: 'Brand identity, art direction',
    summary: 'A refund offer set like a contract instead of a stunt.',
    palette: ['#12202C', '#E4674A', '#F1EDE4', '#5B6B77'],
    accent: '#E4674A',
    typeface: 'Space Grotesk',
    monogram: 'VZ',
    problem: 'A refund offer that sounded like a gimmick because it was written like one.',
    move:
      'State the terms as terms. Ten million views, full refund, in plain numbers on every surface.',
    system:
      'Wordmark, a coordinate annotation system for each route, a ticker treatment for the threshold figure, and a booking flow that shows the refund condition before the price.',
    result:
      'The offer stopped reading as a stunt once it was set like a contract. Applications now cite the terms back verbatim.',
    images: [
      '/work/voyaze-01.webp',
      '/work/voyaze-02.webp',
      '/work/voyaze-03.webp',
      '/work/voyaze-04.webp',
      '/work/voyaze-05.webp',
      '/work/voyaze-06.webp',
    ],
    wordmarkWide: '/work/voyaze-01w.webp',
  },
  {
    slug: 'voxaris',
    name: 'VOXARIS',
    sector: 'Games · Issue-Led',
    categories: 'Identity / Campaign',
    year: 2026,
    role: 'Brand identity, art direction',
    summary: 'Protest print, not packaging — every release ships its own sheet.',
    palette: ['#0B0B0F', '#4DE0A8', '#F0EDE6', '#6E7178'],
    accent: '#4DE0A8',
    typeface: 'Anton',
    monogram: 'VX',
    problem:
      'Games about real events, presented in the visual language of entertainment franchises.',
    move:
      'Borrow the grammar of protest print. A game about a real event should arrive the way news of it did — a sheet pasted up in public, not a box on a shelf.',
    system:
      'Display lockup, a poster system that scales from key art down to a single sheet pasted at eye level, phosphor reserved for the call to action, and a title-card grammar that credits the source event.',
    result:
      'Every release now ships with its own printed sheet. Players share the poster before they share the trailer.',
    images: [
      '/work/voxaris-01.webp',
      '/work/voxaris-02.webp',
      '/work/voxaris-03.webp',
      '/work/voxaris-04.webp',
      '/work/voxaris-05.webp',
      '/work/voxaris-06.webp',
    ],
    wordmarkWide: '/work/voxaris-01w.webp',
  },
  {
    slug: 'sentinel',
    name: 'SENTINEL',
    sector: 'Access & Security',
    categories: 'Identity / Product',
    year: 2026,
    role: 'Brand identity, art direction',
    summary: 'A lock that reads as architecture rather than surveillance.',
    palette: ['#1A1C1E', '#4A4FE0', '#EDEDEA', '#8E949A'],
    accent: '#4A4FE0',
    typeface: 'IBM Plex Sans',
    monogram: 'SN',
    problem:
      "Biometric hardware marketed with fear, which is exactly what people don't want by their front door.",
    move:
      'Sell the calm, not the threat. A lock should feel like architecture, not like surveillance.',
    system:
      'Wordmark, a faceplate annotation system, indigo used only on the active-state indicator, and interface type legible in a dark hallway at arm’s length.',
    result:
      'Nothing in the identity mentions intrusion. The product now sits in specification decks next to door hardware, not alarm systems.',
    images: [
      '/work/sentinel-01.webp',
      '/work/sentinel-02.webp',
      '/work/sentinel-03.webp',
      '/work/sentinel-04.webp',
      '/work/sentinel-05.webp',
      '/work/sentinel-06.webp',
    ],
    wordmarkWide: '/work/sentinel-01w.webp',
  },
];

/**
 * Alt text for a board, by its index in `images`. Describes what the board is for rather
 * than restating that it is a picture — a screen reader user needs "wordmark" or "colour
 * system", not "image".
 */
export function boardAlt(project: Project, index: number): string {
  const purpose = [
    'wordmark',
    'colour system, four palette swatches',
    'application artifact',
    `type specimen set in ${project.typeface}`,
    `construction of the ${project.monogram} monogram on its grid`,
    'lockups at four sizes',
  ][index];
  return `${project.name} — ${purpose ?? 'brand board'}`;
}

export function getProject(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}

export function nextProject(slug: string): Project {
  const i = projects.findIndex((p) => p.slug === slug);
  return projects[(i + 1) % projects.length];
}
